apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "plural.migration-name" . }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: migrator
        image: "{{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ include "plural.imageTag" . }}"
        command: ["/opt/app/bin/plural",  "migrate"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: plural-env
        - secretRef:
            name: plural-migration-env
        env:
        {{ include "plural.env" . | nindent 8 }}
      restartPolicy: Never
  backoffLimit: 5
{{ if .Values.scanPackages }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: scan-packages-{{ randAlphaNum 4 | lower }}
  labels:
{{ include "plural.labels" . | indent 4 }}
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: plural
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: cron
        image: "{{ .Values.cron.image }}:{{ include "plural.imageTag" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: plural-env
        env:
        - name: CRON
          value: Task.VersionScan
        {{ include "plural.env" . | nindent 8 }}
        resources:
          {{- toYaml .Values.cron.resources | nindent 10 }}
{{ end }}
{{ if .Values.createHydraDb }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-hydra-db
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: plural
      containers:
      - name: createdb
        image: postgres:14
        command: 
        - "/bin/sh"
        - "-c"
        - |
          psql "$POSTGRES_URL" -c "CREATE DATABASE hydra"
        envFrom:
        - secretRef:
            name: plural-env
  backoffLimit: 5
{{ end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hydra-migration-{{ .Values.image.tag | default .Chart.AppVersion | sha256sum | trunc 8 }}
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hydra-migration
        image: "{{ .Values.hydra.image.repository }}:{{ .Values.hydra.image.tag }}"
        imagePullPolicy: {{ .Values.hydra.image.pullPolicy }}
        command: ["hydra"]
        args: ["migrate", "sql", "-e", "--yes"]
        env:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: plural-hydra
              key: dsn
