apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: plural-plural
  labels:
    app: postgres
    db: plural
  {{ include "plural.labels" . | nindent 4 }}
spec:
  teamId: plural
  volume:
    size: {{ .Values.postgres.plural.size }}
  numberOfInstances: 2
  {{ if .Values.postgres.plural.resources }}
  resources:
  {{ mergeOverwrite .Values.postgres.default.resources .Values.postgres.plural.resources | toYaml | nindent 4 }}
  {{ end }}
  users:
    plural:  # database owner
    - superuser
    - createdb
  databases:
    plural: plural  # dbname: owner
  postgresql:
    version: "13"
    parameters:
      max_connections: '101'
  {{- with .Values.postgres.plural.nodeAffinity }}
  nodeAffinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.postgres.plural.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  sidecars:
  - image: gcr.io/pluralsh/postgres-exporter:0.8.0
    name: exporter
    ports:
    - containerPort: 9187
      name: http-metrics
      protocol: TCP
    env:
    - name: "DATA_SOURCE_URI"
      value: "127.0.0.1:5432/plural?sslmode=disable"
    - name: "DATA_SOURCE_USER"
      valueFrom:
        secretKeyRef:
          name: postgres.plural-plural.credentials.postgresql.acid.zalan.do
          key: username
    - name: "DATA_SOURCE_PASS"
      valueFrom:
        secretKeyRef:
          name: postgres.plural-plural.credentials.postgresql.acid.zalan.do
          key: password
    livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /
        port: http-metrics
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      livenessProbe:
      failureThreshold: 6
      httpGet:
        path: /
        port: http-metrics
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: plural-master
  labels:
    spilo-role: master
    {{ include "plural.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  - name: http-metrics
    port: 9187
    targetPort: http-metrics
  selector:
    spilo-role: master
    cluster-name: plural-plural
---
apiVersion: v1
kind: Service
metadata:
  name: plural-master-scrape
  labels:
    spilo-role: master
    {{ include "plural.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  - name: http-metrics
    port: 9187
    targetPort: http-metrics
  selector:
    spilo-role: master
---
apiVersion: v1
kind: Service
metadata:
  name: plural-replica
  labels:
    spilo-role: replica
    {{ include "plural.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  - name: http-metrics
    port: 9187
    targetPort: http-metrics
  selector:
    spilo-role: replica
    cluster-name: plural-plural
