apiVersion: v1
kind: ConfigMap
metadata:
  name: plural-registry-config
  labels:
{{ include "plural.labels" . | indent 4 }}
data:
  config.yml: |-
{{ toYaml .Values.registry.configData | indent 4 }}
  cert.pem: {{ .Values.secrets.jwt_cert | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plural-registry-aws-config
  labels:
{{ include "plural.labels" . | indent 4 }}
data:
  config: >-
    [default]
    region=us-east-2
---
apiVersion: v1
kind: Secret
metadata:
  name: plural-registry-secret
  labels:
{{ include "plural.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.registry.secrets.haSharedSecret }}
  haSharedSecret: {{ .Values.registry.secrets.haSharedSecret | b64enc | quote }}
  {{- else }}
  haSharedSecret: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}