apiVersion: v1
kind: Secret
metadata:
  name: watchman-env
  labels:
{{ include "chartmart.labels" . | indent 4 }}
type: Opaque
data:
  GIT_URL: {{ .Values.secrets.git_url | b64enc | quote }}
  REPO_ROOT: {{ .Values.secrets.repo_root | b64enc | quote }}
  WEBHOOK_SECRET: {{ .Values.secrets.webhook_secret | b64enc | quote }}
  ERLANG_COOKIE: {{ .Values.secrets.erlang | b64enc | quote }}
  GIT_USER: {{ .Values.git_user }}
  GIT_EMAIL: {{ .Values.git_email }}
---
apiVersion: v1
kind: Secret
metadata:
  name: watchman-ssh
  labels:
{{ include "chartmart.labels" . | indent 4 }}
type: Opaque
data:
  id_rsa: {{ .Values.secrets.id_rsa | b64enc | quote }}
  id_rsa.pub: {{ .Values.secrets.id_rsa_pub | b64enc | quote }}
  known_hosts: {{ .Values.secrets.known_hosts | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: watchman-conf
  labels:
{{ include "chartmart.labels" . | indent 4 }}
type: Opaque
data:
  config.yml: {{ .Values.secrets.config | b64enc | quote }}
  key: {{ .Values.secrets.key | b64enc | quote }}