parser: "@babel/eslint-parser"
extends: pluralsh
rules:
  import/prefer-default-export: 'off'
  react/no-unstable-nested-components: 'off'
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
overrides:
  - files:
    - "*.test.ts"
    - "*.test.tsx"
    env:
      jest: true
