apiVersion: v1
appVersion: "1.0"
description: A helm chart for installing chartmart
name: chartmart
sources:
- https://github.com/michaeljguarino/chartmart
maintainers:
- name: michaeljguarino
  email: mguarino46@gmail.com
version: 0.1.8
