apiVersion: v1
kind: Service
metadata:
  name: forge-api
  labels:
    app: forge-api
{{ include "forge.labels" . | indent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: {{ .Values.api.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: 4369
    targetPort: epmd
    protocol: TCP
    name: epmd
  selector:
    app.kubernetes.io/name: forge-api
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: chartmuseum
  labels:
{{ include "forge.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: chartmuseum
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: forge-www
  labels:
    app: forge-www
{{ include "forge.labels" . | indent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: {{ .Values.www.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: forge-www
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: forge-registry
  labels:
    app: forge-registry
{{ include "forge.labels" . | indent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: forge-registry
    app.kubernetes.io/instance: {{ .Release.Name }}