apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmart-api
  labels:
{{ include "chartmart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: chartmart-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chartmart-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: chartmart
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: chartmart-env
        env:
        - name: HOST
          value: {{ .Values.ingress.dns }}
        - name: DEPLOYED_AT
          value: {{ .Release.Time }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbPasswordSecret }}
              key: postgresql-password
        - name: GCP_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: chartmart-serviceaccount
              key: gcp.json
        - name: GCS_BUCKET
          value: {{ .Values.api.bucket }}
        ports:
        - name: http
          containerPort: {{ .Values.api.port }}
          protocol: TCP
        - name: epmd
          containerPort: 4369
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum
  labels:
{{ include "chartmart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: chartmuseum
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chartmuseum
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
    {{- end }}
      containers:
      - name: chartmuseum
        image: "{{ .Values.chartmuseum.repository }}:{{ .Values.chartmuseum.tag }}"
        imagePullPolicy: {{ .Values.chartmuseum.pullPolicy }}
        env:
        - name: PORT
          value: '8080'
        - name: DEPLOYED_AT
          value: {{ .Release.Time }}
        - name: DEPTH
          value: '1'
        - name: CONTEXT_PATH
          value: '/cm'
        - name: STORAGE
          value: google
        - name: STORAGE_GOOGLE_BUCKET
          value: {{ .Values.chartmuseum.bucket }}
        - name: STORAGE_GOOGLE_PREFIX
          value: ""
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /home/chartmuseum/.gcp/gcp.json
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /cm/health
            port: http
        readinessProbe:
          httpGet:
            path: /cm/health
            port: http
        volumeMounts:
        - name: gcp
          mountPath: "/home/chartmuseum/.gcp"
          readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: gcp
        secret:
          secretName: chartmart-serviceaccount
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmart-www
  labels:
{{ include "chartmart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.www.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: chartmart-www
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chartmart-www
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: www
        image: "{{ .Values.www.image }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DEPLOYED_AT
          value: {{ .Release.Time }}
        ports:
        - name: http
          containerPort: {{ .Values.www.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.www.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}