apiVersion: v1
kind: Secret
metadata:
  name: chartmart-env
  labels:
{{ include "chartmart.labels" . | indent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwt | b64enc | quote }}
  SECRET_KEY_BASE: {{ randAlphaNum 10 | b64enc | quote }}
  ERLANG_COOKIE: {{ .Values.secrets.erlang | b64enc | quote }}
  JWT_PRIVATE_KEY: {{ .Values.secrets.jwt_pk | b64enc | quote }}
  JWT_CERT: {{ .Values.secrets.jwt_cert | b64enc | quote }}
  JWT_ISS: {{ .Values.secrets.jwt_iss | b64enc | quote }}
  JWT_AUD: {{ .Values.secrets.jwt_aud | b64enc | quote }}
  AES_KEY: {{ .Values.secrets.aes_key | b64enc | quote }}
  STRIPE_SECRET: {{ .Values.secrets.stripe_secret | b64enc | quote }}
  SENGRID_API_KEY: {{ .Values.secrets.sendgrid_secret | b64enc | quote }}
---
{{ if .Values.admin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: chartmart-migration-env
  labels:
{{ include "chartmart.labels" . | indent 4 }}
type: Opaque
data:
  ADMIN_EMAIL: {{ .Values.admin.email | b64enc | quote }}
  ADMIN_NAME: {{ .Values.admin.name | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.password | b64enc | quote }}
  PUBLISHER_NAME: {{ .Values.admin.publisher | b64enc | quote }}
  PUBLISHER_DESCRIPTION: {{ .Values.admin.publisher_description | b64enc | quote }}
{{ end }}