apiVersion: v2
name: plural
description: A helm chart for installing plural
appVersion: 0.10.18
version: 0.10.18
dependencies:
  - name: hydra
    repository: https://k8s.ory.sh/helm/charts
    version: 0.26.5
  - name: test-base
    repository: https://pluralsh.github.io/module-library
    version: 0.1.10
    condition: test-base.enabled
maintainers:
  - email: mjg@plural.sh
    name: michaeljguarino
sources:
  - https://github.com/pluralsh/plural
