replicaCount: 2
rabbitmqNamespace: rabbitmq
influxNamespace: influx

rbac:
  serviceAccountAnnotations: {}

configOverlays:
- name: stripe-secret-key
  spec:
    folder: secrets
    subfolder: stripe
    name: Stripe Secret Key
    documentation: secret key for platform stripe account
    updates:
    - path: ['plural', 'secrets', 'stripe_secret']
- name: stripe-public-key
  spec:
    folder: secrets
    subfolder: stripe
    name: Stripe Publishable Key
    documentation: publishable key for platform stripe account
    updates:
    - path: ['plural', 'secrets', 'stripe_publishable_key']
- name: stripe-connect-id
  spec:
    folder: secrets
    subfolder: stripe
    name: Stripe Connect Id
    documentation: id for stripe connect account
    updates:
    - path: ['plural', 'secrets', 'stripe_connect_id']
- name: zerossl-access-key
  spec:
    folder: secrets
    subfolder: zerossl
    name: ZeroSSL Access Key
    documentation: key for zerossl account
    updates:
    - path: ['plural', 'secrets', 'zerossl_access_key']
- name: zoom-client-id
  spec:
    folder: secrets
    subfolder: zoom
    name: Zoom Client Id
    documentation: client id for zoom aouth
    updates:
    - path: ['plural', 'secrets', 'zoom_client_id']
- name: zoom-client-secret
  spec:
    folder: secrets
    subfolder: zoom
    name: Zoom Client Secret
    documentation: client secret for zoom aouth
    updates:
    - path: ['plural', 'secrets', 'zoom_client_secret']
- name: cloudflare-token
  spec:
    folder: secrets
    subfolder: cloudflare
    name: Cloudflare Token
    documentation: token for cloudflare auth
    updates:
    - path: ['plural', 'secrets', 'cloudflare_token']
- name: cloudflare-zone
  spec:
    folder: secrets
    subfolder: cloudflare
    name: Cloudflare Zone
    documentation: zone id for cloudflare dns
    updates:
    - path: ['plural', 'secrets', 'cloudflare_zone']
- name: sendgrid-secret
  spec:
    folder: secrets
    subfolder: sendgrid
    name: Sendgrid Secret
    documentation: secret for sendgrid authentication
    updates:
    - path: ['plural', 'secrets', 'sendgrid_secret']
- name: github-client-id
  spec:
    folder: secrets
    subfolder: github
    name: Github Client Id
    documentation: client id for github oauth
    updates:
    - path: ['plural', 'secrets', 'github', 'client_id']
- name: github-client-secret
  spec:
    folder: secrets
    subfolder: github
    name: Github Client secret
    documentation: client secret for github oauth
    updates:
    - path: ['plural', 'secrets', 'github', 'client_secret']
- name: gitlab-client-id
  spec:
    name: Gitlab Client Id
    folder: secrets
    subfolder: gitlab
    documentation: client id for gitlab authentication
    updates:
    - path: ['plural', 'secrets', 'gitlab', 'client_id']
- name: gitlab-client-secret
  spec:
    name: Gitlab Client Secret
    folder: secrets
    subfolder: gitlab
    documentation: client secret for gitlab authentication
    updates:
    - path: ['plural', 'secrets', 'gitlab', 'client_secret']
- name: google-client-id
  spec:
    name: Google Client Id
    folder: secrets
    subfolder: google
    documentation: client id for google authentication
    updates:
    - path: ['plural', 'secrets', 'google', 'client_id']
- name: google-client-secret
  spec:
    name: Google Client Secret
    folder: secrets
    subfolder: google
    documentation: client secret for google authentication
    updates:
    - path: ['plural', 'secrets', 'google', 'client_secret']
- name: google-org-id
  spec:
    name: Google Org ID
    folder: secrets
    subfolder: google
    documentation: your gcp organization id
    updates:
    - path: ['plural', 'secrets', 'google', 'org_id']
- name: google-credentials
  spec:
    name: Google Credentials
    folder: secrets
    subfolder: google
    documentation: service account credentials to use for gcp demos
    updates:
    - path: ['plural', 'secrets', 'google', 'gcp_credentials']
- name: workos-client-id
  spec:
    name: WorkOS Client Id
    folder: secrets
    subfolder: workos
    documentation: client id for workos authentication
    updates:
    - path: ['plural', 'secrets', 'workos', 'client_id']
- name: workos-api-key
  spec:
    name: WorkOS Api Key
    folder: secrets
    subfolder: workos
    documentation: api key for workos authentication
    updates:
    - path: ['plural', 'secrets', 'workos', 'api_key']
- name: workos-webhook-secret
  spec:
    name: WorkOS Webhook Secret
    folder: secrets
    subfolder: workos
    documentation: signing secret for workos webhooks 
    updates:
    - path: ['plural', 'secrets', 'workos', 'webhook_secret']
- name: sentry-dsn
  spec:
    name: Sentry DSN
    folder: secrets
    subfolder: sentry
    documentation: dsn address for sentry error collection
    updates:
    - path: ['plural', 'sentryDsn']
- name: api-cpu
  labels:
    platform.plural.sh/component: plural-api
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: API CPU
    documentation: cpu requests for api deployment
    updates:
    - path: ['plural', 'api', 'resources', 'requests', 'cpu']
- name: api-mem
  labels:
    platform.plural.sh/component: plural-api
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: API Memory
    documentation: memory requests for api deployment
    updates:
    - path: ['plural', 'api', 'resources', 'requests', 'memory']
- name: rtc-cpu
  labels:
    platform.plural.sh/component: plural-rtc
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: rtc cpu
    documentation: cpu requests for rtc deployment
    updates:
    - path: ['plural', 'rtc', 'resources', 'requests', 'cpu']
- name: rtc-mem
  labels:
    platform.plural.sh/component: plural-rtc
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: rtc memory
    documentation: memory requests for rtc deployment
    updates:
    - path: ['plural', 'rtc', 'resources', 'requests', 'memory']
- name: worker-cpu
  labels:
    platform.plural.sh/component: plural-worker
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: worker cpu
    documentation: cpu requests for worker deployment
    updates:
    - path: ['plural', 'worker', 'resources', 'requests', 'cpu']
- name: worker-mem
  labels:
    platform.plural.sh/component: plural-worker
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: worker memory
    documentation: memory requests for worker deployment
    updates:
    - path: ['plural', 'worker', 'resources', 'requests', 'memory']
- name: registry-cpu
  labels:
    platform.plural.sh/component: plural-registry
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: registry cpu
    documentation: cpu requests for registry deployment
    updates:
    - path: ['plural', 'registry', 'resources', 'requests', 'cpu']
- name: registry-mem
  labels:
    platform.plural.sh/component: plural-registry
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: registry memory
    documentation: memory requests for registry deployment
    updates:
    - path: ['plural', 'registry', 'resources', 'requests', 'memory']
- name: chartmuseum-cpu
  labels:
    platform.plural.sh/component: chartmuseum
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: cpu
  spec:
    name: chartmuseum cpu
    documentation: cpu requests for chartmuseum deployment
    updates:
    - path: ['plural', 'chartmuseum', 'resources', 'requests', 'cpu']
- name: chartmuseum-mem
  labels:
    platform.plural.sh/component: chartmuseum
    platform.plural.sh/kind: deployment
    platform.plural.sh/resource: memory
  spec:
    name: chartmuseum memory
    documentation: memory requests for chartmuseum deployment
    updates:
    - path: ['plural', 'chartmuseum', 'resources', 'requests', 'memory']

secrets:
  jwt: dummy
  erlang: dummy
  jwt_pk: dummy
  jwt_cert: dummy
  jwt_iss: dummy
  jwt_aud: dummy
  aes_key: dummy

admin:
  enabled: false

postgres:
  plural:
    resources: {}
    size: 50Gi
  hydra:
    resources: {}
    size: 25Gi
  default:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: '2'
        memory: 1Gi

image:
  repository: dkr.plural.sh/plural/plural
  tag: '0.3.4' ## PLRL-REPLACE[  tag: '%s']
  pullPolicy: Always

rtc:
  repository: dkr.plural.sh/plural/rtc
  tag: '0.3.4' ## PLRL-REPLACE[  tag: '%s']
  resources: {}
  replicaCount: 2

worker:
  repository: dkr.plural.sh/plural/worker
  tag: '0.3.4' ## PLRL-REPLACE[  tag: '%s']
  minReplicas: 1
  maxReplicas: 10
  resources: {}
  replicaCount: 2

www:
  image: dkr.plural.sh/plural/plural-www
  tag: '0.3.4' ## PLRL-REPLACE[  tag: '%s']
  port: 80
  resources: {}
  replicaCount: 2

cron:
  image: dkr.plural.sh/plural/cron
  tag: '0.3.4' ## PLRL-REPLACE[  tag: '%s']

imagePullSecrets:
- name: plural-creds

provider: aws
region: us-east-1

api:
  port: 4000
  bucket: plural-assets
  resources: {}

dbPasswordSecret: plural.plural-plural.credentials.postgresql.acid.zalan.do
rabbitPasswordSecret: plural-rabbitmq

crons:
- cronName: plural-dkr-scan
  cronModule: Task.Docker
  crontab: "0 0 * * *"
  envVars: []
- cronName: plrl-login-prune
  cronModule: Prune.Passwordless
  crontab: "10 0 * * *"
  envVars: []
- cronName: plrl-prune-queues
  cronModule: Prune.Queues
  crontab: "15 0 * * *"
  envVars: []
- cronName: plrl-stale-tests
  cronModule: Task.StaleTests
  crontab: "30 0 * * *"
  envVars: []
- cronName: plrl-prune-invites
  cronModule: Prune.Invites
  crontab: "45 0 * * *"
  envVars: []

hydraSecrets:
  dsn: memory
  system: dummy
  cookie: dummy

hydraImage:
  # ORY Hydra image
  repository: gcr.io/pluralsh/oryd/hydra
  # ORY Hydra version
  tag: v1.8.5
  # Image pull policy
  pullPolicy: IfNotPresent

autoscaling:
  enabled: true

hydra:
  replicaCount: 2

  image:
    repository: gcr.io/pluralsh/oryd/hydra

  maester:
    enabled: false
  hydra:
    dangerousForceHttp: true
    existingSecret: false
    autoMigrate: false
    config:
      ttl:
        id_token: 12h
        access_token: 12h
        refresh_token: 96h

  pdb:
    enabled: true
  deployment:
    autoscaling:
      enabled: false
    
  ingress:
    public:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/use-regex: "true"
  
chartmuseum:
  resources: {}
  replicaCount: 1
  rbac:
    serviceAccountAnnotations: {}
  repository: dkr.plural.sh/plural/chartmuseum
  tag: v0.13.2
  bucket: plural-charts
  pullPolicy: Always

registry:
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  podDisruptionBudget: {}
  nodeSelector: {}
  tolerations: []
  rbac:
    serviceAccountAnnotations: {}
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

  persistence:
    accessMode: ReadWriteOnce
    enabled: false
    size: 10Gi

  securityContext:
    enabled: false
    runAsUser: 1000
    fsGroup: 1000

  secrets:
    haSharedSecret: ""

  image: 
    repository: gcr.io/pluralsh/registry
    tag: 2.7.2

  configData:
    version: 0.1
    notifications:
      endpoints:
      - name: plural
        url: http://plural-api:4000/dkr/callback
        timeout: 500ms
        threshold: 5
        backoff: 1s
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    prometheus:
      enabled: true
    auth:
      token:
        realm: plural.piazza.app/dkr
        service: plural.piazza.app/dkr
        issuer: plural.piazza.app
        rootcertbundle: /etc/docker/registry/cert.pem
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

postgresql:
  image:
    registry: gcr.io
    repository: pluralsh/postgres
    tag: 11.7.0-debian-10-r9
  metrics:
    enabled: true
    image:
      registry: gcr.io
      repository: pluralsh/postgres-exporter
      tag: 0.8.0
    serviceMonitor:
      enabled: true
  postgresqlExtendedConf:
    max_connections: 100
  postgresqlUsername: plural
  postgresqlDatabase: plural

rabbitmqCredentials:
  namespace: "rabbitmq"

rabbitmq:
  metrics:
    enabled: true

influxdb:
  resources:
    requests:
      memory: 256Mi
      cpu: 0.2
  env:
  - name: INFLUXDB_DB
    value: plural
  setDefaultUser:
    enabled: true
    user:
      username: plural
      password: null

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  dns: app.plural.sh
  dkr_dns: dkr.plural.sh
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-path: /socket
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
  
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

test-base:
  enabled: false
  repository: plural
  testName: plural-integration
  promoteTag: warm