name: Daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  graphql:
    name: 'Update GraphQL TS Schema'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: www
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PLURAL_BOT_PAT }}
      - name: Read Node.js version from package.json
        run: echo ::set-output name=nodeVersion::$(node -p "require('./package.json').engines.node")
        id: engines
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}
      - name: 'Update Schema'
        run: |
          yarn install --immutable
          yarn graphql:codegen
      - name: 'Commit and push'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'www'
          author_name: Plural Bot
          author_email: gh-bot@plural.sh
          commit: --signoff
          default_author: user_info
          message: "Update GraphQL TS Schema"
          push: true
