name: www-ci

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/www.yaml"
      - "www/**"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/www.yaml"
      - "www/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: www
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - shell: bash
        run: |
          [ ! -d "node_modules" ] && npm ci
      - shell: bash
        run: npm run lint
