name: Plural UI
on:
  push:
    branches:
      - master
      - "renovate/frontend/*"
    paths:
      - ".github/workflows/www.yaml"
      - "www/**"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/www.yaml"
      - "www/**"
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: ./www
          file: ./www/Dockerfile
          push: false
  test:
    name: Unit test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: www
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Read Node.js version from package.json
        run: echo ::set-output name=nodeVersion::$(node -p "require('./package.json').engines.node")
        id: engines
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}
      - run: yarn --immutable
      - run: yarn test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: www
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Read Node.js version from package.json
        run: echo ::set-output name=nodeVersion::$(node -p "require('./package.json').engines.node")
        id: engines
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}
      - run: yarn --immutable
      - run: yarn lint
  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest
    env:
      CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
    defaults:
      run:
        shell: bash
        working-directory: www
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Read Node.js version from package.json
        run: echo ::set-output name=nodeVersion::$(node -p "require('./package.json').engines.node")
        id: engines
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}
      - run: yarn # Should run the --immutable in the CI by default
      - run: cd e2e && yarn
      - run: yarn e2e
      - uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          fields: workflow,repo,commit,author,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CYPRESS_WEBHOOK }}
      - name: Upload Screenshots and Videos to Slack
        if: failure()
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        with:
          token: ${{ secrets.SLACK_CYPRESS_TOKEN }}
          workdir: www/e2e/cypress
          channels: cypress-artifacts
          message-text: "See the attached videos and screenshots for more information."
