apiVersion: v1
kind: Service
metadata:
  name: plural-ai
  labels:
    app: plural-ai
{{ include "plural.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.ai.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: plural-ai
    app.kubernetes.io/instance: {{ .Release.Name }}